// Generated by jextract

package sh.adelessfox.wgpu_native;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;

/**
 * {@snippet lang=c :
 * struct WGPUHubReport {
 *     WGPURegistryReport adapters;
 *     WGPURegistryReport devices;
 *     WGPURegistryReport queues;
 *     WGPURegistryReport pipelineLayouts;
 *     WGPURegistryReport shaderModules;
 *     WGPURegistryReport bindGroupLayouts;
 *     WGPURegistryReport bindGroups;
 *     WGPURegistryReport commandBuffers;
 *     WGPURegistryReport renderBundles;
 *     WGPURegistryReport renderPipelines;
 *     WGPURegistryReport computePipelines;
 *     WGPURegistryReport pipelineCaches;
 *     WGPURegistryReport querySets;
 *     WGPURegistryReport buffers;
 *     WGPURegistryReport textures;
 *     WGPURegistryReport textureViews;
 *     WGPURegistryReport samplers;
 * }
 * }
 */
public final class WGPUHubReport {

    WGPUHubReport() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        WGPURegistryReport.layout().withName("adapters"),
        WGPURegistryReport.layout().withName("devices"),
        WGPURegistryReport.layout().withName("queues"),
        WGPURegistryReport.layout().withName("pipelineLayouts"),
        WGPURegistryReport.layout().withName("shaderModules"),
        WGPURegistryReport.layout().withName("bindGroupLayouts"),
        WGPURegistryReport.layout().withName("bindGroups"),
        WGPURegistryReport.layout().withName("commandBuffers"),
        WGPURegistryReport.layout().withName("renderBundles"),
        WGPURegistryReport.layout().withName("renderPipelines"),
        WGPURegistryReport.layout().withName("computePipelines"),
        WGPURegistryReport.layout().withName("pipelineCaches"),
        WGPURegistryReport.layout().withName("querySets"),
        WGPURegistryReport.layout().withName("buffers"),
        WGPURegistryReport.layout().withName("textures"),
        WGPURegistryReport.layout().withName("textureViews"),
        WGPURegistryReport.layout().withName("samplers")
    ).withName("WGPUHubReport");

    /**
     * The layout of this struct
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    private static final GroupLayout adapters$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("adapters"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport adapters
     * }
     */
    public static GroupLayout adapters$layout() {
        return adapters$LAYOUT;
    }

    private static final long adapters$OFFSET = $LAYOUT.byteOffset(groupElement("adapters"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport adapters
     * }
     */
    public static long adapters$offset() {
        return adapters$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport adapters
     * }
     */
    public static MemorySegment adapters(MemorySegment struct) {
        return struct.asSlice(adapters$OFFSET, adapters$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport adapters
     * }
     */
    public static void adapters(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, adapters$OFFSET, adapters$LAYOUT.byteSize());
    }

    private static final GroupLayout devices$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("devices"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport devices
     * }
     */
    public static GroupLayout devices$layout() {
        return devices$LAYOUT;
    }

    private static final long devices$OFFSET = $LAYOUT.byteOffset(groupElement("devices"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport devices
     * }
     */
    public static long devices$offset() {
        return devices$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport devices
     * }
     */
    public static MemorySegment devices(MemorySegment struct) {
        return struct.asSlice(devices$OFFSET, devices$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport devices
     * }
     */
    public static void devices(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, devices$OFFSET, devices$LAYOUT.byteSize());
    }

    private static final GroupLayout queues$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("queues"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport queues
     * }
     */
    public static GroupLayout queues$layout() {
        return queues$LAYOUT;
    }

    private static final long queues$OFFSET = $LAYOUT.byteOffset(groupElement("queues"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport queues
     * }
     */
    public static long queues$offset() {
        return queues$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport queues
     * }
     */
    public static MemorySegment queues(MemorySegment struct) {
        return struct.asSlice(queues$OFFSET, queues$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport queues
     * }
     */
    public static void queues(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, queues$OFFSET, queues$LAYOUT.byteSize());
    }

    private static final GroupLayout pipelineLayouts$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("pipelineLayouts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport pipelineLayouts
     * }
     */
    public static GroupLayout pipelineLayouts$layout() {
        return pipelineLayouts$LAYOUT;
    }

    private static final long pipelineLayouts$OFFSET = $LAYOUT.byteOffset(groupElement("pipelineLayouts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport pipelineLayouts
     * }
     */
    public static long pipelineLayouts$offset() {
        return pipelineLayouts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport pipelineLayouts
     * }
     */
    public static MemorySegment pipelineLayouts(MemorySegment struct) {
        return struct.asSlice(pipelineLayouts$OFFSET, pipelineLayouts$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport pipelineLayouts
     * }
     */
    public static void pipelineLayouts(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, pipelineLayouts$OFFSET, pipelineLayouts$LAYOUT.byteSize());
    }

    private static final GroupLayout shaderModules$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("shaderModules"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport shaderModules
     * }
     */
    public static GroupLayout shaderModules$layout() {
        return shaderModules$LAYOUT;
    }

    private static final long shaderModules$OFFSET = $LAYOUT.byteOffset(groupElement("shaderModules"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport shaderModules
     * }
     */
    public static long shaderModules$offset() {
        return shaderModules$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport shaderModules
     * }
     */
    public static MemorySegment shaderModules(MemorySegment struct) {
        return struct.asSlice(shaderModules$OFFSET, shaderModules$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport shaderModules
     * }
     */
    public static void shaderModules(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, shaderModules$OFFSET, shaderModules$LAYOUT.byteSize());
    }

    private static final GroupLayout bindGroupLayouts$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("bindGroupLayouts"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport bindGroupLayouts
     * }
     */
    public static GroupLayout bindGroupLayouts$layout() {
        return bindGroupLayouts$LAYOUT;
    }

    private static final long bindGroupLayouts$OFFSET = $LAYOUT.byteOffset(groupElement("bindGroupLayouts"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport bindGroupLayouts
     * }
     */
    public static long bindGroupLayouts$offset() {
        return bindGroupLayouts$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport bindGroupLayouts
     * }
     */
    public static MemorySegment bindGroupLayouts(MemorySegment struct) {
        return struct.asSlice(bindGroupLayouts$OFFSET, bindGroupLayouts$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport bindGroupLayouts
     * }
     */
    public static void bindGroupLayouts(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, bindGroupLayouts$OFFSET, bindGroupLayouts$LAYOUT.byteSize());
    }

    private static final GroupLayout bindGroups$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("bindGroups"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport bindGroups
     * }
     */
    public static GroupLayout bindGroups$layout() {
        return bindGroups$LAYOUT;
    }

    private static final long bindGroups$OFFSET = $LAYOUT.byteOffset(groupElement("bindGroups"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport bindGroups
     * }
     */
    public static long bindGroups$offset() {
        return bindGroups$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport bindGroups
     * }
     */
    public static MemorySegment bindGroups(MemorySegment struct) {
        return struct.asSlice(bindGroups$OFFSET, bindGroups$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport bindGroups
     * }
     */
    public static void bindGroups(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, bindGroups$OFFSET, bindGroups$LAYOUT.byteSize());
    }

    private static final GroupLayout commandBuffers$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("commandBuffers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport commandBuffers
     * }
     */
    public static GroupLayout commandBuffers$layout() {
        return commandBuffers$LAYOUT;
    }

    private static final long commandBuffers$OFFSET = $LAYOUT.byteOffset(groupElement("commandBuffers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport commandBuffers
     * }
     */
    public static long commandBuffers$offset() {
        return commandBuffers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport commandBuffers
     * }
     */
    public static MemorySegment commandBuffers(MemorySegment struct) {
        return struct.asSlice(commandBuffers$OFFSET, commandBuffers$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport commandBuffers
     * }
     */
    public static void commandBuffers(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, commandBuffers$OFFSET, commandBuffers$LAYOUT.byteSize());
    }

    private static final GroupLayout renderBundles$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("renderBundles"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport renderBundles
     * }
     */
    public static GroupLayout renderBundles$layout() {
        return renderBundles$LAYOUT;
    }

    private static final long renderBundles$OFFSET = $LAYOUT.byteOffset(groupElement("renderBundles"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport renderBundles
     * }
     */
    public static long renderBundles$offset() {
        return renderBundles$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport renderBundles
     * }
     */
    public static MemorySegment renderBundles(MemorySegment struct) {
        return struct.asSlice(renderBundles$OFFSET, renderBundles$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport renderBundles
     * }
     */
    public static void renderBundles(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, renderBundles$OFFSET, renderBundles$LAYOUT.byteSize());
    }

    private static final GroupLayout renderPipelines$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("renderPipelines"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport renderPipelines
     * }
     */
    public static GroupLayout renderPipelines$layout() {
        return renderPipelines$LAYOUT;
    }

    private static final long renderPipelines$OFFSET = $LAYOUT.byteOffset(groupElement("renderPipelines"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport renderPipelines
     * }
     */
    public static long renderPipelines$offset() {
        return renderPipelines$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport renderPipelines
     * }
     */
    public static MemorySegment renderPipelines(MemorySegment struct) {
        return struct.asSlice(renderPipelines$OFFSET, renderPipelines$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport renderPipelines
     * }
     */
    public static void renderPipelines(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, renderPipelines$OFFSET, renderPipelines$LAYOUT.byteSize());
    }

    private static final GroupLayout computePipelines$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("computePipelines"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport computePipelines
     * }
     */
    public static GroupLayout computePipelines$layout() {
        return computePipelines$LAYOUT;
    }

    private static final long computePipelines$OFFSET = $LAYOUT.byteOffset(groupElement("computePipelines"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport computePipelines
     * }
     */
    public static long computePipelines$offset() {
        return computePipelines$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport computePipelines
     * }
     */
    public static MemorySegment computePipelines(MemorySegment struct) {
        return struct.asSlice(computePipelines$OFFSET, computePipelines$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport computePipelines
     * }
     */
    public static void computePipelines(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, computePipelines$OFFSET, computePipelines$LAYOUT.byteSize());
    }

    private static final GroupLayout pipelineCaches$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("pipelineCaches"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport pipelineCaches
     * }
     */
    public static GroupLayout pipelineCaches$layout() {
        return pipelineCaches$LAYOUT;
    }

    private static final long pipelineCaches$OFFSET = $LAYOUT.byteOffset(groupElement("pipelineCaches"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport pipelineCaches
     * }
     */
    public static long pipelineCaches$offset() {
        return pipelineCaches$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport pipelineCaches
     * }
     */
    public static MemorySegment pipelineCaches(MemorySegment struct) {
        return struct.asSlice(pipelineCaches$OFFSET, pipelineCaches$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport pipelineCaches
     * }
     */
    public static void pipelineCaches(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, pipelineCaches$OFFSET, pipelineCaches$LAYOUT.byteSize());
    }

    private static final GroupLayout querySets$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("querySets"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport querySets
     * }
     */
    public static GroupLayout querySets$layout() {
        return querySets$LAYOUT;
    }

    private static final long querySets$OFFSET = $LAYOUT.byteOffset(groupElement("querySets"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport querySets
     * }
     */
    public static long querySets$offset() {
        return querySets$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport querySets
     * }
     */
    public static MemorySegment querySets(MemorySegment struct) {
        return struct.asSlice(querySets$OFFSET, querySets$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport querySets
     * }
     */
    public static void querySets(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, querySets$OFFSET, querySets$LAYOUT.byteSize());
    }

    private static final GroupLayout buffers$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("buffers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport buffers
     * }
     */
    public static GroupLayout buffers$layout() {
        return buffers$LAYOUT;
    }

    private static final long buffers$OFFSET = $LAYOUT.byteOffset(groupElement("buffers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport buffers
     * }
     */
    public static long buffers$offset() {
        return buffers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport buffers
     * }
     */
    public static MemorySegment buffers(MemorySegment struct) {
        return struct.asSlice(buffers$OFFSET, buffers$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport buffers
     * }
     */
    public static void buffers(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, buffers$OFFSET, buffers$LAYOUT.byteSize());
    }

    private static final GroupLayout textures$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("textures"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport textures
     * }
     */
    public static GroupLayout textures$layout() {
        return textures$LAYOUT;
    }

    private static final long textures$OFFSET = $LAYOUT.byteOffset(groupElement("textures"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport textures
     * }
     */
    public static long textures$offset() {
        return textures$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport textures
     * }
     */
    public static MemorySegment textures(MemorySegment struct) {
        return struct.asSlice(textures$OFFSET, textures$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport textures
     * }
     */
    public static void textures(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, textures$OFFSET, textures$LAYOUT.byteSize());
    }

    private static final GroupLayout textureViews$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("textureViews"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport textureViews
     * }
     */
    public static GroupLayout textureViews$layout() {
        return textureViews$LAYOUT;
    }

    private static final long textureViews$OFFSET = $LAYOUT.byteOffset(groupElement("textureViews"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport textureViews
     * }
     */
    public static long textureViews$offset() {
        return textureViews$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport textureViews
     * }
     */
    public static MemorySegment textureViews(MemorySegment struct) {
        return struct.asSlice(textureViews$OFFSET, textureViews$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport textureViews
     * }
     */
    public static void textureViews(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, textureViews$OFFSET, textureViews$LAYOUT.byteSize());
    }

    private static final GroupLayout samplers$LAYOUT = (GroupLayout)$LAYOUT.select(groupElement("samplers"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * WGPURegistryReport samplers
     * }
     */
    public static GroupLayout samplers$layout() {
        return samplers$LAYOUT;
    }

    private static final long samplers$OFFSET = $LAYOUT.byteOffset(groupElement("samplers"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * WGPURegistryReport samplers
     * }
     */
    public static long samplers$offset() {
        return samplers$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * WGPURegistryReport samplers
     * }
     */
    public static MemorySegment samplers(MemorySegment struct) {
        return struct.asSlice(samplers$OFFSET, samplers$LAYOUT.byteSize());
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * WGPURegistryReport samplers
     * }
     */
    public static void samplers(MemorySegment struct, MemorySegment fieldValue) {
        MemorySegment.copy(fieldValue, 0L, struct, samplers$OFFSET, samplers$LAYOUT.byteSize());
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

