// Generated by jextract

package sh.adelessfox.wgpu_native;

import java.lang.foreign.*;
import java.util.function.Consumer;

import static java.lang.foreign.MemoryLayout.PathElement.groupElement;
import static java.lang.foreign.ValueLayout.OfLong;

/**
 * {@snippet lang=c :
 * struct WGPURegistryReport {
 *     size_t numAllocated;
 *     size_t numKeptFromUser;
 *     size_t numReleasedFromUser;
 *     size_t elementSize;
 * }
 * }
 */
public final class WGPURegistryReport {

    WGPURegistryReport() {
        // Should not be called directly
    }

    private static final GroupLayout $LAYOUT = MemoryLayout.structLayout(
        wgpu_h.C_LONG_LONG.withName("numAllocated"),
        wgpu_h.C_LONG_LONG.withName("numKeptFromUser"),
        wgpu_h.C_LONG_LONG.withName("numReleasedFromUser"),
        wgpu_h.C_LONG_LONG.withName("elementSize")
    ).withName("WGPURegistryReport");

    /**
     * The layout of this struct
     */
    public static GroupLayout layout() {
        return $LAYOUT;
    }

    private static final OfLong numAllocated$LAYOUT = (OfLong)$LAYOUT.select(groupElement("numAllocated"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t numAllocated
     * }
     */
    public static OfLong numAllocated$layout() {
        return numAllocated$LAYOUT;
    }

    private static final long numAllocated$OFFSET = $LAYOUT.byteOffset(groupElement("numAllocated"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t numAllocated
     * }
     */
    public static long numAllocated$offset() {
        return numAllocated$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t numAllocated
     * }
     */
    public static long numAllocated(MemorySegment struct) {
        return struct.get(numAllocated$LAYOUT, numAllocated$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t numAllocated
     * }
     */
    public static void numAllocated(MemorySegment struct, long fieldValue) {
        struct.set(numAllocated$LAYOUT, numAllocated$OFFSET, fieldValue);
    }

    private static final OfLong numKeptFromUser$LAYOUT = (OfLong)$LAYOUT.select(groupElement("numKeptFromUser"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t numKeptFromUser
     * }
     */
    public static OfLong numKeptFromUser$layout() {
        return numKeptFromUser$LAYOUT;
    }

    private static final long numKeptFromUser$OFFSET = $LAYOUT.byteOffset(groupElement("numKeptFromUser"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t numKeptFromUser
     * }
     */
    public static long numKeptFromUser$offset() {
        return numKeptFromUser$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t numKeptFromUser
     * }
     */
    public static long numKeptFromUser(MemorySegment struct) {
        return struct.get(numKeptFromUser$LAYOUT, numKeptFromUser$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t numKeptFromUser
     * }
     */
    public static void numKeptFromUser(MemorySegment struct, long fieldValue) {
        struct.set(numKeptFromUser$LAYOUT, numKeptFromUser$OFFSET, fieldValue);
    }

    private static final OfLong numReleasedFromUser$LAYOUT = (OfLong)$LAYOUT.select(groupElement("numReleasedFromUser"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t numReleasedFromUser
     * }
     */
    public static OfLong numReleasedFromUser$layout() {
        return numReleasedFromUser$LAYOUT;
    }

    private static final long numReleasedFromUser$OFFSET = $LAYOUT.byteOffset(groupElement("numReleasedFromUser"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t numReleasedFromUser
     * }
     */
    public static long numReleasedFromUser$offset() {
        return numReleasedFromUser$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t numReleasedFromUser
     * }
     */
    public static long numReleasedFromUser(MemorySegment struct) {
        return struct.get(numReleasedFromUser$LAYOUT, numReleasedFromUser$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t numReleasedFromUser
     * }
     */
    public static void numReleasedFromUser(MemorySegment struct, long fieldValue) {
        struct.set(numReleasedFromUser$LAYOUT, numReleasedFromUser$OFFSET, fieldValue);
    }

    private static final OfLong elementSize$LAYOUT = (OfLong)$LAYOUT.select(groupElement("elementSize"));

    /**
     * Layout for field:
     * {@snippet lang=c :
     * size_t elementSize
     * }
     */
    public static OfLong elementSize$layout() {
        return elementSize$LAYOUT;
    }

    private static final long elementSize$OFFSET = $LAYOUT.byteOffset(groupElement("elementSize"));

    /**
     * Offset for field:
     * {@snippet lang=c :
     * size_t elementSize
     * }
     */
    public static long elementSize$offset() {
        return elementSize$OFFSET;
    }

    /**
     * Getter for field:
     * {@snippet lang=c :
     * size_t elementSize
     * }
     */
    public static long elementSize(MemorySegment struct) {
        return struct.get(elementSize$LAYOUT, elementSize$OFFSET);
    }

    /**
     * Setter for field:
     * {@snippet lang=c :
     * size_t elementSize
     * }
     */
    public static void elementSize(MemorySegment struct, long fieldValue) {
        struct.set(elementSize$LAYOUT, elementSize$OFFSET, fieldValue);
    }

    /**
     * Obtains a slice of {@code arrayParam} which selects the array element at {@code index}.
     * The returned segment has address {@code arrayParam.address() + index * layout().byteSize()}
     */
    public static MemorySegment asSlice(MemorySegment array, long index) {
        return array.asSlice(layout().byteSize() * index);
    }

    /**
     * The size (in bytes) of this struct
     */
    public static long sizeof() { return layout().byteSize(); }

    /**
     * Allocate a segment of size {@code layout().byteSize()} using {@code allocator}
     */
    public static MemorySegment allocate(SegmentAllocator allocator) {
        return allocator.allocate(layout());
    }

    /**
     * Allocate an array of size {@code elementCount} using {@code allocator}.
     * The returned segment has size {@code elementCount * layout().byteSize()}.
     */
    public static MemorySegment allocateArray(long elementCount, SegmentAllocator allocator) {
        return allocator.allocate(MemoryLayout.sequenceLayout(elementCount, layout()));
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, Arena arena, Consumer<MemorySegment> cleanup) {
        return reinterpret(addr, 1, arena, cleanup);
    }

    /**
     * Reinterprets {@code addr} using target {@code arena} and {@code cleanupAction} (if any).
     * The returned segment has size {@code elementCount * layout().byteSize()}
     */
    public static MemorySegment reinterpret(MemorySegment addr, long elementCount, Arena arena, Consumer<MemorySegment> cleanup) {
        return addr.reinterpret(layout().byteSize() * elementCount, arena, cleanup);
    }
}

